config/routes.rb
Webtool::Application.routes.draw do
 

  get "pages/help"

  get "pages/contact"

  get "reports/index"

  get "report/index"

  resources :clients

  resources :orgs do
	get :autocomplete_orgname, :on => :collection
  end
  
  
 
  devise_for :users, :controllers => { :sessions => "users/sessions", :passwords => "users/passwords", }

  resources :indivs
  
  resources :territories
  
  resources :reports
  
  match 'help' => 'pages#help', :as => 'help'
  match 'contact' => 'pages#contact', :as => 'contact'

   root :to => "indivs#index"

end

app/models/indiv.rb
class Indiv < ActiveRecord::Base
	has_many :pxdxes
	has_many :orgs, :through => :pxdxes
	belongs_to :territory
	
	
	#def to_param
		#hms_piid.parameterize
	#end
	
	def self.search(search)  
	  if search  
		where('first LIKE ? OR last LIKE ? OR zip LIKE ? or city like ?', "%#{search}%", "%#{search}%" ,"%#{search}%", "%#{search}%")
	  else  
		scoped 
	  end  
	end
end

app/controllers/indivs_controller.rb
class IndivsController < AuthorizedController
  # GET /indivs
  # GET /indivs.xml
  helper_method :sort_column, :sort_direction
 # caches_action :index
  
  
  
  def index
    @indivs = Indiv.search(params[:search]).order(sort_column + ' '+ sort_direction).paginate(:per_page => 20, :page => params[:page])
	
	respond_to do |format|
	  format.js
      format.html # index.html.erb
      format.xml  { render :xml => @indivs }
    end
  end

  # GET /indivs/1
  # GET /indivs/1.xml
  def show
    @indiv = Indiv.find(params[:id])
	
	@orgs = @indiv.orgs
	
	respond_to do |format|
		format.html # show.html.erb
		format.xml  { render :xml => @indiv }
	end
  end
	
 

  # GET /indivs/new
  # GET /indivs/new.xml
  def new
    @indiv = Indiv.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @indiv }
    end
  end

  # GET /indivs/1/edit
  def edit
    @indiv = Indiv.find(params[:id])
  end

  # POST /indivs
  # POST /indivs.xml
  def create
    @indiv = Indiv.new(params[:indiv])

    respond_to do |format|
      if @indiv.save
        format.html { redirect_to(@indiv, :notice => 'Indiv was successfully created.') }
        format.xml  { render :xml => @indiv, :status => :created, :location => @indiv }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @indiv.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /indivs/1
  # PUT /indivs/1.xml
  def update
    @indiv = Indiv.find(params[:id])

    respond_to do |format|
      if @indiv.update_attributes(params[:indiv])
        format.html { redirect_to(@indiv, :notice => 'Indiv was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @indiv.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /indivs/1
  # DELETE /indivs/1.xml
  def destroy
    @indiv = Indiv.find(params[:id])
    @indiv.destroy

    respond_to do |format|
      format.html { redirect_to(indivs_url) }
      format.xml  { head :ok }
    end
  end
  
private
  
  def sort_column
	Indiv.column_names.include?(params[:sort]) ? params[:sort] : "bucket_1_rank"
  end
  
  
  def sort_direction
	%w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/helpers/indivs_helper.rb
module IndivsHelper
end

app/views/indivs/_advanced_search.html.erb
<%= form_for(@indiv) do |f| %>
  <% if @indiv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@indiv.errors.count, "error") %> prohibited this indiv from being saved:</h2>

      <ul>
      <% @indiv.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="field">
    <%= f.label :first %><br />
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br />
    <%= f.text_field :last %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>

  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>

  <div class="field">
    <%= f.label :specialty %><br />
    <%= f.text_field :specialty %>
  </div>
  
  <div class="field">
    <%= f.label :pract_type %><br />
    <%= f.text_field :pract_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/indivs/_form.html.erb
<%= form_for(@indiv) do |f| %>
  <% if @indiv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@indiv.errors.count, "error") %> prohibited this indiv from being saved:</h2>

      <ul>
      <% @indiv.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :hms_piid %><br />
    <%= f.text_field :hms_piid %>
  </div>
  <div class="field">
    <%= f.label :first %><br />
    <%= f.text_field :first %>
  </div>
  <div class="field">
    <%= f.label :last %><br />
    <%= f.text_field :last %>
  </div>
  <div class="field">
    <%= f.label :address1 %><br />
    <%= f.text_field :address1 %>
  </div>
  <div class="field">
    <%= f.label :address2 %><br />
    <%= f.text_field :address2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br />
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br />
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br />
    <%= f.text_field :zip %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :specialty %><br />
    <%= f.text_field :specialty %>
  </div>
  <div class="field">
    <%= f.label :pract_type %><br />
    <%= f.text_field :pract_type %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/indivs/_indiv_search.html.erb
<% form_tag indivs_path, :method => 'get', :id => "indivs_search" do %>
	<%= hidden_field_tag :direction, params[:direction] %>  
	<%= hidden_field_tag :sort, params[:sort] %>
	<p>
		<%= text_field_tag :search, params[:search], :id => "search_bar", :class => "default-value", :value => "Search for a keyword, city, state or zip" %>
		<input type = "submit" value="Search Practitioners" class="button_red">
	</p>
<% end %>

app/views/indivs/_indivs.html.erb
<table id="indivs_table">
 
	<%= will_paginate @indivs %>
	 <tr>
    
    <th> <%= sortable "first", "First"%></th>
    <th><%= sortable "last", "Last" %></th>
	<th><%= sortable  "bucket_1_rank", "Hypo Rank"%></th>
    <th><%=sortable  "bucket_2_rank", "Liver Rank"%></th>
    <th><%=sortable  "bucket_3_rank", "Ortho Rank"%></th>
    <th><%=sortable  "bucket_4_rank", "Cancer Rank"%></th>
 
  
  </tr>

<% @indivs.each do |indiv| %>
  <tr class="<%= cycle('even','odd') %>">
    <td><%=link_to "#{indiv.first}", indiv_path(indiv) %></td>
    <td><%= link_to "#{indiv.last}", indiv_path(indiv) %></td>
    <td><%= indiv.bucket_1_rank %></td>
    <td><%= indiv.bucket_2_rank %></td>
    <td><%= indiv.bucket_3_rank %></td>
    <td><%= indiv.bucket_4_rank %></td>
   
   

  </tr>
<% end %>
</table>

app/views/indivs/edit.html.erb
<h1>Editing indiv</h1>

<%= render 'form' %>

<%= link_to 'Show', @indiv %> |
<%= link_to 'Back', indivs_path %>

app/views/indivs/index.html.erb
<h1>Practitioners</h1>

<div id="indivs"> <%= render 'indivs' %> </div>


<br />

app/views/indivs/index.js.erb
$('#indivs').html('<%= escape_javascript(render("indivs")) %>');

app/views/indivs/new.html.erb
<h1>New indiv</h1>

<%= render 'form' %>

<%= link_to 'Back', indivs_path %>

app/views/indivs/show.html.erb
<p id="notice"><%= notice %></p>



<div id = "indiv_details">


<!-- affiliation info -->
	<div class="right">
		<p>
	    	<%= link_to 'Go Back >>' , indivs_path, :class => "red" %>
	     </p>
	     <br/>
		<b class ="red"> Affiliated Organizations: </b>
	
		<% @orgs.each do |org| %>
		
		<p>
		<%= link_to org.orgname, org_path(org)  %>
		</p>
		<% end %>
	</div>


<!-- practitioner info -->
	  <h2 class="title">Practitioner Information </h2>
	
		<p>
		  <b class="red">First Name:</b>
		  <%= @indiv.first %>
		</p>
		
		<p>
		  <b class="red">Last Name:</b>
		  <%= @indiv.last %>
	  
	  </p>
	
	
	
		<p>
		  <b class="red">Address:</b>
		  <%= @indiv.address1 %>
		</p>
	
		
	  <b class="red">Address2:</b>
	  		<%= @indiv.address2 %>
		</p>
	
		<p>
		  <b class="red">City:</b>
		  <%= @indiv.city %>
		</p>
	
		<p>
		  <b class="red">State:</b>
		  <%= @indiv.state %>
		</p>
	
		<p>
		  <b class="red">Zipcode:</b>
		  <%= @indiv.zip %>
		</p>
	
		<p>
		  <b class="red">Phone:</b>
		  <%= @indiv.phone %>
		</p>
	
		<p>
		  <b class="red">Specialty:</b>
		  <%= @indiv.specialty %>
		</p>
	

<!-- Ranking Info -->
	<table width="25%" id="buckets_table">
		<tr>
			<th>Hypo Rank </th>
			<th>Ortho Rank</th>
			<th>Liver Rank </th>
			<th>Cancer Rank </th>
			
		</tr>
		<tr>
			<td> <%= @indiv.bucket_1_rank %> </td>
			<td> <%= @indiv.bucket_2_rank %> </td>
			<td> <%= @indiv.bucket_3_rank %> </td>
			<td> <%= @indiv.bucket_4_rank %> </td>
			
		<tr>
			
			
		</tr>
			
	</table>
	
	

</div>