config/routes.rb
Webtool::Application.routes.draw do
 

  get "pages/help"

  get "pages/contact"

  get "reports/index"

  get "report/index"

  resources :clients

  resources :orgs do
	get :autocomplete_orgname, :on => :collection
  end
  
  
 
  devise_for :users, :controllers => { :sessions => "users/sessions", :passwords => "users/passwords", }

  resources :indivs
  
  resources :territories
  
  resources :reports
  
  match 'help' => 'pages#help', :as => 'help'
  match 'contact' => 'pages#contact', :as => 'contact'

   root :to => "indivs#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability
  
  def initialize(user)
	  user ||= User.new
	  if user.admin?
		can :manage, :all
	  else
		can :read, :all
	  end
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/indiv.rb
class Indiv < ActiveRecord::Base
	has_many :pxdxes
	has_many :orgs, :through => :pxdxes
	belongs_to :territory
	
	
	#def to_param
		#hms_piid.parameterize
	#end
	
	def self.search(search)  
	  if search  
		where('first LIKE ? OR last LIKE ? OR zip LIKE ? or city like ?', "%#{search}%", "%#{search}%" ,"%#{search}%", "%#{search}%")
	  else  
		scoped 
	  end  
	end
end

app/models/install.rb
class Install < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/models/org.rb
class Org < ActiveRecord::Base
	has_many :pxdxes
	has_many :indivs, :through => :pxdxes
	belongs_to :territory
	
	
	cattr_reader :per_page
	@@per_page = 15
	
	def self.search(search)  
	  if search  
		where('orgname LIKE ? OR city LIKE ? OR zipcode LIKE ?', "%#{search}%", "%#{search}%", "%#{search}")
	  else  
		scoped 
	  end  
	end
	
	def self.find_territories(id)
		find_all_by_zipcode(id)
	end
	
	
	acts_as_gmappable
	
		def gmaps4rails_address
			"#{self.address1},#{self.address2},#{self.city},#{self.state},#{self.zipcode}"
		end
end

app/models/pxdx.rb
class Pxdx < ActiveRecord::Base
	belongs_to :indiv
	belongs_to :org
end

app/models/territory.rb
class Territory < ActiveRecord::Base
	
	has_many :indivs
	has_many :orgs
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable and :timeoutable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  
  has_one :territory
end

app/controllers/indivs_controller.rb
class IndivsController < AuthorizedController
  # GET /indivs
  # GET /indivs.xml
  helper_method :sort_column, :sort_direction
 # caches_action :index
  
  
  
  def index
    @indivs = Indiv.search(params[:search]).order(sort_column + ' '+ sort_direction).paginate(:per_page => 20, :page => params[:page])
	
	respond_to do |format|
	  format.js
      format.html # index.html.erb
      format.xml  { render :xml => @indivs }
    end
  end

  # GET /indivs/1
  # GET /indivs/1.xml
  def show
    @indiv = Indiv.find(params[:id])
	
	@orgs = @indiv.orgs
	
	respond_to do |format|
		format.html # show.html.erb
		format.xml  { render :xml => @indiv }
	end
  end
	
 

  # GET /indivs/new
  # GET /indivs/new.xml
  def new
    @indiv = Indiv.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @indiv }
    end
  end

  # GET /indivs/1/edit
  def edit
    @indiv = Indiv.find(params[:id])
  end

  # POST /indivs
  # POST /indivs.xml
  def create
    @indiv = Indiv.new(params[:indiv])

    respond_to do |format|
      if @indiv.save
        format.html { redirect_to(@indiv, :notice => 'Indiv was successfully created.') }
        format.xml  { render :xml => @indiv, :status => :created, :location => @indiv }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @indiv.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /indivs/1
  # PUT /indivs/1.xml
  def update
    @indiv = Indiv.find(params[:id])

    respond_to do |format|
      if @indiv.update_attributes(params[:indiv])
        format.html { redirect_to(@indiv, :notice => 'Indiv was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @indiv.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /indivs/1
  # DELETE /indivs/1.xml
  def destroy
    @indiv = Indiv.find(params[:id])
    @indiv.destroy

    respond_to do |format|
      format.html { redirect_to(indivs_url) }
      format.xml  { head :ok }
    end
  end
  
private
  
  def sort_column
	Indiv.column_names.include?(params[:sort]) ? params[:sort] : "bucket_1_rank"
  end
  
  
  def sort_direction
	%w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/controllers/orgs_controller.rb
class OrgsController < AuthorizedController
  # GET /orgs
  # GET /orgs.xml
  
  layout 'orgs'
  
  helper_method :sort_column, :sort_direction
 # caches_action :index
  
  autocomplete :org, :orgname
  
  def index
    @orgs = Org.search(params[:search]).order(sort_column + ' '+ sort_direction).paginate(:per_page => 20, :page => params[:page])

    respond_to do |format|
	  format.js
      format.html # index.html.erb
      format.xml  { render :xml => @orgs }
    end
  end

  # GET /orgs/1
  # GET /orgs/1.xml
  def show
    @org = Org.find(params[:id])
	@json = @org.to_gmaps4rails
	@indivs = @org.indivs
	

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @org }
    end
  end

  # GET /orgs/new
  # GET /orgs/new.xml
  def new
    @org = Org.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @org }
    end
  end

  # GET /orgs/1/edit
  def edit
    @org = Org.find(params[:id])
  end

  # POST /orgs
  # POST /orgs.xml
  def create
    @org = Org.new(params[:org])

    respond_to do |format|
      if @org.save
        format.html { redirect_to(@org, :notice => 'Org was successfully created.') }
        format.xml  { render :xml => @org, :status => :created, :location => @org }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @org.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /orgs/1
  # PUT /orgs/1.xml
  def update
    @org = Org.find(params[:id])

    respond_to do |format|
      if @org.update_attributes(params[:org])
        format.html { redirect_to(@org, :notice => 'Org was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @org.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /orgs/1
  # DELETE /orgs/1.xml
  def destroy
    @org = Org.find(params[:id])
    @org.destroy

    respond_to do |format|
      format.html { redirect_to(orgs_url) }
      format.xml  { head :ok }
    end
  end
  
  def territories
	@orgs = Org.find_all_by_zipcode('44484')
  end
  private
  
  def sort_column
	Org.column_names.include?(params[:sort]) ? params[:sort] : "org_bucket_1_rank"
  end
  
  
  def sort_direction
	%w[asc desc].include?(params[:direction]) ? params[:direction] : "desc"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def help
  end

  def contact
  end

end

app/controllers/users_controller.rb
class Users  < Devise::SessionsController

layout 'home_ltr'


end

app/helpers/application_helper.rb
module ApplicationHelper


  def sortable(column, title = nil)  
    title ||= column.titleize  
	css_class = (column == sort_column) ? "current #{sort_direction}" : nil  
    direction = (column == sort_column && sort_direction == "desc") ? "asc" : "desc"  
    link_to title, params.merge(:sort => column, :direction => direction, :page => nil ), {:class => css_class} 
  end  


end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/indivs_helper.rb
module IndivsHelper
end

app/helpers/orgs_helper.rb
module OrgsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/report_helper.rb
module ReportHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/territories_helper.rb
module TerritoriesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>inatable </title>

<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :all %>
<%= csrf_meta_tag %>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
<!--[if IE 6]><link rel="stylesheet" type="text/css" href="/css/ie6.css" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" type="text/css" href="/css/ie.css" media="screen" /><![endif]-->
<link rel="shortcut icon" href="images/favicon.ico" />

<script type="text/javascript">


var active_color = '#000'; // Colour of user provided text
var inactive_color = '#444'; // Colour of default text

/**
 * No need to modify anything below this line
 */

$(document).ready(function() {
  $("input.default-value").css("color", inactive_color);
  var default_values = new Array();
  $("input.default-value").focus(function() {
    if (!default_values[this.id]) {
      default_values[this.id] = this.value;
    }
    if (this.value == default_values[this.id]) {
      this.value = '';
      this.style.color = active_color;
    }
    $(this).blur(function() {
      if (this.value == '') {
        this.style.color = inactive_color;
        this.value = default_values[this.id];
      }
    });
  });
});
</script>
</head>

<body>


<!-- Begin Container -->
<div class="container_12">

<!-- Begin Header -->
	<div class="grid_12">
		<div id="header">

					

			<ul class="nav">
				<li> <%= link_to "Account Settings", edit_user_registration_path %> </li>
				<li><%= link_to "Help", help_path %> </li>
				<li><%= link_to "Contact", contact_path %> </li>
			</ul>
		
				
			<h1 id="branding">
				<%= image_tag('inatable_logo.png') %> 
			</h1>
		
					<div id="user_nav" style="font-size: 12px;">
							<% if user_signed_in? %>  
								Signed in as <%= current_user.email %>.  
								<%= link_to "Sign out", destroy_user_session_path %>  
						  <% else %>  
							<p> </p>  
					<% end %>  
				</div>	
		</div>
				
	</div>



<!--begin main -->
<div id="main">
	
	<!-- user nav -->

		
	<!-- main content -->
	<div class="grid_8">
		<div id="content">
			<p class= "notice"> <%= notice %> </p>
			<p class="alert"> <%= alert %>  </p>
			<%= yield %>
		</div>
	</div>
		
	<!-- sidebar -->
		<div class="grid_4">
			<div id="sidebar">
			
				<% form_tag indivs_path, :method => 'get', :id => "indivs_search" do %>
						<%= hidden_field_tag :direction, params[:direction] %>  
						<%= hidden_field_tag :sort, params[:sort] %>
						<p>
							<%= text_field_tag :search, params[:search], :id => "search_bar", :class => "default-value", :value => "Search for a keyword, city, state or zip" %>
							<input type = "submit" value="Search Practitioners" class="button_red">
						</p>
				<% end %>
			
			<!-- Begin Nav Links -->
					
					
					<div class="square">
						<%= image_tag('building.png')%>
						<%= link_to "Organizations", orgs_path %>
					</div>
				
					<div class="square">
						<%= image_tag('user.png')%>
						<%= link_to "Practitioners", indivs_path %>	
					</div>
				
					<div class="square" >
						<%= image_tag('map.png')%>
						<%= link_to "Territories", territories_path %>  
					</div>
				 
					<div class="square">
							<%= image_tag('stats.png')%>
							<%= link_to "Reports", reports_path %>
						</div>	
				
			</div>
		</div>
	
	

	<!-- end sidebar -->

<!-- end main -->
</div>




<div class="clear"></div>





<!-- begin footer -->
<div class="grid_12" id="site_info">
	
	
<div class="box">
	<p>Copyright 2011 implied labs </p>

</div>
</div>
<div class="clear"></div>
</div>

</html>

app/views/layouts/application_backup.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>HMS WebTool</title>

<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :all %>
<%= csrf_meta_tag %>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
<!--[if IE 6]><link rel="stylesheet" type="text/css" href="/css/ie6.css" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" type="text/css" href="/css/ie.css" media="screen" /><![endif]-->
</head>

<body>


<!-- Begin Container -->
<div class="container_12">

	<div class="grid_12">
		<div id="header">

					

			<ul class="nav">
				<li><a href="/"> Home </a> </li>
				<li><a href="/indivs"> Individuals </a> </li>
				<li><a href="/orgs"> Orgs </a> </li>
				<li><a href=""> Help </a> </li>
				
				
			</ul>
		
				
			<h1 id="branding">
				<%= image_tag('hms_logo.gif') %> 
				
			
				
			</h1>
		
					<div class="right" style="font-size: 12px;">
				<% if user_signed_in? %>  
							Signed in as <%= current_user.email %>.  
							<%= link_to "Sign out", destroy_user_session_path %>  
						  <% else %>  
							<p> </p>  
					<% end %>  
				</div>	
		</div>
				
</div>



<!--begin main -->
<div id="main">
	
	<!-- user nav -->

		
	<!-- main content -->
	<div class="grid_8">
		<div id="content">
			<p class= "notice"> <%= notice %> </p>
			<p class="alert"> <%= alert %>  </p>
			<%= yield %>
		</div>
	</div>
		
	<!-- sidebar -->
		<div class="grid_4">
			<div id="sidebar">
			
			<%= render 'indiv_search' %>
			
			<div id = "links" class = "right">
				<%= link_to "Advanced Search", indivs_path %>  
				</p>
				<p>
				<%= link_to "Territories", indivs_path %> 
			
				</p>
				<p>
				<%= link_to "Stats/Reports", orgs_path %>
				</p>
				<p>
				<%= link_to "Account Settings", edit_user_registration_path %>
				</p>
			</div>
		</div>
	
	
</div>
	


</div>




<div class="clear"></div>


<!--end of hidden divs displaying column sizes. Begin templates and prototypes for forms, accordions, jquery, etc -->


<!-- begin footer -->
<div class="grid_12" id="site_info">
	
	
<div class="box">
	<p>Copyright 2010 HealthMarket Science </p>
\
</div>
</div>
<div class="clear"></div>
</div>
<%= yield :scripts %>
<script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="js/jquery-ui-1.8.5.custom.js"></script>
<script type="text/javascript" src="js/jquery-fluid16.js"></script>
</body>
</html>

app/views/layouts/application_old_layout.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>inatable </title>

<%= stylesheet_link_tag :all %>
 <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.js' %>

<%= csrf_meta_tag %>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
<!--[if IE 6]><link rel="stylesheet" type="text/css" href="/css/ie6.css" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" type="text/css" href="/css/ie.css" media="screen" /><![endif]-->
<link rel="shortcut icon" href="images/favicon.ico" />

<script type="text/javascript">
/**
 * Written by Rob Schmitt, The Web Developer's Blog
 * http://webdeveloper.beforeseven.com/
 */

/**
 * The following variables may be adjusted
 */
var active_color = '#000'; // Colour of user provided text
var inactive_color = '#ccc'; // Colour of default text

/**
 * No need to modify anything below this line
 */

$(document).ready(function() {
  $("input.default-value").css("color", inactive_color);
  var default_values = new Array();
  $("input.default-value").focus(function() {
    if (!default_values[this.id]) {
      default_values[this.id] = this.value;
    }
    if (this.value == default_values[this.id]) {
      this.value = '';
      this.style.color = active_color;
    }
    $(this).blur(function() {
      if (this.value == '') {
        this.style.color = inactive_color;
        this.value = default_values[this.id];
      }
    });
  });
});
</script>
</head>

<body>


<!-- Begin Container -->
<div class="container_12">

<!-- Begin Header -->
	<div class="grid_12">
		<div id="user_nav" style="font-size: 12px;">
							<% if user_signed_in? %>  
								Signed in as <%= current_user.email %>.  
								<%= link_to "Sign out", destroy_user_session_path %>  
						  <% else %>  
							<p> </p>  
					<% end %>  
				</div>			
		<div id="header">
			
				<% form_tag indivs_path, :method => 'get', :id => "indivs_search", :class => "right" do %>
						<%= hidden_field_tag :direction, params[:direction] %>  
						<%= hidden_field_tag :sort, params[:sort] %>
						<p>
							<%= text_field_tag :search, params[:search], :id => "search_bar", :class => "default-value", :value => "Search for a keyword, city, state or zip" %>
							<input type = "submit" value="Search Practitioners" class="button_red">
						</p>
				<% end %>
			

					

		
				
			<h1 id="branding">
				<%= image_tag('inatable_logo.png') %> 
			</h1>
		
			<ul class="nav">
				<li> <%= link_to "Account Settings", edit_user_registration_path %> </li>
				<li><%= link_to "Help", help_path %> </li>
				<li><%= link_to "Contact", contact_path %> </li>
			</ul>
			
						
		</div>
				
	</div>



<!--begin main -->
<div id="main">
	
	<!-- user nav -->

		
	<!-- main content -->
	<div class="grid_8">
		<div id="content">
			<p class= "notice"> <%= notice %> </p>
			<p class="alert"> <%= alert %>  </p>
			<%= yield %>
		</div>
	</div>
		
	<!-- sidebar -->
		<div class="grid_4">
			<div id="sidebar">
			
			<!-- Begin Nav Links -->
					
					
					<div class="square">
						<%= image_tag('building.png')%>
						<%= link_to "Organizations", orgs_path %>
					</div>
				
					<div class="square">
						<%= image_tag('user.png')%>
						<%= link_to "Practitioners", indivs_path %>	
					</div>
				
					<div class="square" >
						<%= image_tag('map.png')%>
						<%= link_to "Territories", territories_path %>  
					</div>
				 
					<div class="square">
							<%= image_tag('stats.png')%>
							<%= link_to "Reports", reports_path %>
						</div>	
				
			</div>
		</div>
	
	

	<!-- end sidebar -->

<!-- end main -->
</div>




<div class="clear"></div>





<!-- begin footer -->
<div class="grid_12" id="site_info">
	
	
<div class="box">
	<p>Copyright 2011 implied labs </p>
	<%- # Javascript at the bottom for fast page loading -%>

  <%- # Grab Google CDN's jQuery. fall back to local if necessary -%>
  <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.js' %>
  <%= javascript_include_tag :all %>
</div>
</div>
<div class="clear"></div>
</div>

</html>

app/views/layouts/home_ltr_blank.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>inatable</title>

<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :all %>
<%= csrf_meta_tag %>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
<!--[if IE 6]><link rel="stylesheet" type="text/css" href="/css/ie6.css" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" type="text/css" href="/css/ie.css" media="screen" /><![endif]-->
</head>

<body>


<!-- Begin Container -->
<div class="container_12">
	<div class="grid_12">

					

	
			
			
		<h1 id="branding">
			<%= image_tag('inatable_logo.png') %> 
		</h1>
	
		<div class="right">
		
		</div>
				
</div>



<!--begin main -->
<div id="main">
	

		
	<!-- main content -->
	<div class="grid_8">
		<div id="content">
		
			<%= yield %>
		</div>
	</div>
		
	<!-- sidebar -->
		<div class="grid_4">
			<div id="sidebar">
			
				<%= link_to "Back to Login Screen", root_url %>
		
				
			</div>
	
	
		</div>
	


</div>




<div class="clear"></div>


<!--end of hidden divs displaying column sizes. Begin templates and prototypes for forms, accordions, jquery, etc -->


<!-- begin footer -->
<div class="grid_12" id="site_info">
	
	
<div class="box">
	<p>Copyright 2011 implied_labs </p>
\
</div>
</div>
<div class="clear"></div>
</div>
<%= yield :scripts %>
<script type="text/javascript" src="js/jquery-1.4.2.min.js"></script>
<script type="text/javascript" src="js/jquery-ui-1.8.5.custom.js"></script>
<script type="text/javascript" src="js/jquery-fluid16.js"></script>
</body>
</html>

app/views/layouts/orgs.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8" />
<title>inatable</title>

<%= stylesheet_link_tag :all %>
 <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.js' %>


<%= csrf_meta_tag %>
<link href='http://fonts.googleapis.com/css?family=Droid+Sans' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Serif' rel='stylesheet' type='text/css'>
<!--[if IE 6]><link rel="stylesheet" type="text/css" href="/css/ie6.css" media="screen" /><![endif]-->
<!--[if IE 7]><link rel="stylesheet" type="text/css" href="/css/ie.css" media="screen" /><![endif]-->
</head>

<!-- load script for default text in search bar -->
<script type="text/javascript">
/**
 * Written by Rob Schmitt, The Web Developer's Blog
 * http://webdeveloper.beforeseven.com/
 */

/**
 * The following variables may be adjusted
 */
var active_color = '#000'; // Colour of user provided text
var inactive_color = '#ccc'; // Colour of default text

/**
 * No need to modify anything below this line
 */

$(document).ready(function() {
  $("input.default-value").css("color", inactive_color);
  var default_values = new Array();
  $("input.default-value").focus(function() {
    if (!default_values[this.id]) {
      default_values[this.id] = this.value;
    }
    if (this.value == default_values[this.id]) {
      this.value = '';
      this.style.color = active_color;
    }
    $(this).blur(function() {
      if (this.value == '') {
        this.style.color = inactive_color;
        this.value = default_values[this.id];
      }
    });
  });
});
</script>
<body>


<!-- Begin Container -->
<div class="container_12">

	<div class="grid_12">
		
		<div id="user_nav" style="font-size: 12px;">
						<% if user_signed_in? %>  
							Signed in as <%= current_user.email %>.  
							<%= link_to "Sign out", destroy_user_session_path %>  
						  <% else %>  
							<p> </p>  
					<% end %>  
				</div>	
		<div id="header">
			
				<% form_tag orgs_path, :method => 'get', :id => "orgs_search", :class => "right" do %>
					<%= hidden_field_tag :direction, params[:direction] %>  
					<%= hidden_field_tag :sort, params[:sort] %>
					<p>
						<%= text_field_tag :search, params[:search], :id => "search_bar", :class => "default-value", :value => "Search for a keyword, city, state or zip"%>
						
					<input type = "submit" value="Search Organizations" class="button_red">
					</p>
				<% end %>

					

			
		
				
			<h1 id="branding">
				<%= image_tag('inatable_logo.png') %> 
			</h1>
			
			<ul class="nav">
				<li><%= link_to "Organizations", orgs_path %></li>
				<li><%= link_to "Practitioners", indivs_path %></li>
				<li><%= link_to "Territories", territories_path %></li>
				<li> <%= link_to "Account Settings", edit_user_registration_path %> </li>
				
			</ul>
		
					
		</div>
				
	</div>



<!--begin main -->
<div id="main">
	
	<!-- user nav -->

		
	<!-- main content -->
	<div class="grid_10">
		<div id="content">
			<p class= "notice"> <%= notice %> </p>
			<p class="alert"> <%= alert %>  </p>
			<%= yield %>
		</div>
	</div>
		
	<!-- sidebar -->
		
	<!-- end sidebar -->

	<!-- end main -->
</div>




<div class="clear"></div>




<!-- begin footer -->
<div class="grid_12" id="site_info">
	
	
<div class="box">
	<p>Copyright 2011 implied labs </p>
</div>
</div>
<div class="clear"></div>
</div>
 <%= javascript_include_tag '//ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.js' %>
  <%= javascript_include_tag :all %>
</body>
</html>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>This would be the place to stick an FAQ, tutorials, common problems, etc.</p>